// METAPAT msdmd collection point.
// Generated by hand until a local collector is wired.

export type MsdmdDeclaration = {
  file: string;
  block: string;
  id: string;
  fields: Record<string, string>;
};

export type MsdmdEdge = {
  from: string;
  to: string;
  kind: string;
  source_block: string;
  source_id: string;
};

export type MsdmdGap = {
  file: string;
  missing: string[];
  note?: string;
};

export type MsdmdCollection = {
  repo: string;
  declarations: MsdmdDeclaration[];
  gaps: MsdmdGap[];
  edges: MsdmdEdge[];
};

export const declarations: MsdmdDeclaration[] = [
  {
    file: "AGENTS.md",
    block: "LLMS",
    id: "project_overview",
    fields: {
      content: "METAPAT is canonical Meta Energy Theory doctrine with planned UCNS -> METAPAT -> EDCM flow.",
    },
  },
  {
    file: "src/metapat/canon.py",
    block: "MODULE_BUILD",
    id: "metapat_canon_core",
    fields: {
      module_name: "metapat.canon",
      module_kind: "schema",
      summary: "exposes current Meta Energy Theory root and primitive extension as importable constants",
    },
  },
  {
    file: "src/metapat/canon.py",
    block: "DOCS",
    id: "metapat_canon_docs",
    fields: {
      source: "AXIOMS.md",
      status: "current",
    },
  },
  {
    file: "src/metapat/canon.py",
    block: "CAPABILITIES",
    id: "metapat_canon_constants",
    fields: {
      exposes: "metapat.canon.definitions",
    },
  },
  {
    file: "src/metapat/validation.py",
    block: "MODULE_BUILD",
    id: "metapat_validation_core",
    fields: {
      module_name: "metapat.validation",
      module_kind: "service",
      summary: "provides deterministic checks for METAPAT theorem validation",
    },
  },
  {
    file: "src/metapat/validation.py",
    block: "CONTRACTS",
    id: "boundary_change_changes_outcome",
    fields: {
      call: "tests.test_contracts.test_boundary_change_changes_outcome",
    },
  },
  {
    file: "src/metapat/validation.py",
    block: "CONTRACTS",
    id: "tensor_before_time",
    fields: {
      call: "tests.test_contracts.test_tensor_precedes_time",
    },
  },
  {
    file: "src/metapat/flow_plan.py",
    block: "MODULE_BUILD",
    id: "metapat_flow_plan",
    fields: {
      module_name: "metapat.flow_plan",
      module_kind: "adapter",
      summary: "records planned UCNS to METAPAT to EDCM flow without implementing the bridge yet",
    },
  },
  {
    file: "src/metapat/flow_plan.py",
    block: "DEPENDENCIES",
    id: "metapat_planned_flow_edges",
    fields: {
      external: "The-Interdependency/ucns, The-Interdependency/edcm",
      direction: "bidirectional",
    },
  },
];

export const gaps: MsdmdGap[] = [
  {
    file: ".agents/skills/llms-build/SKILL.md",
    missing: ["repo-local skill file"],
    note: "hmmm: GitHub write tool blocked this path/content during initial compliance pass; AGENTS.md and llms.txt are present.",
  },
  {
    file: ".agents/skills/test-build/SKILL.md",
    missing: ["repo-local skill file"],
    note: "hmmm: GitHub write tool blocked this path/content during initial compliance pass; CONTRACTS blocks and tests are present.",
  },
  {
    file: ".agents/skills/the-interdependency/SKILL.md",
    missing: ["repo-local skill file"],
    note: "hmmm: GitHub write tool blocked this path/content during initial compliance pass; upstream skill-lib remains canonical.",
  },
  {
    file: "src/metapat/flow_plan.py",
    missing: ["implemented UCNS bridge", "implemented EDCM bridge"],
    note: "planned architecture only; exact APIs are hmmm.",
  },
];

export const edges: MsdmdEdge[] = [
  {
    from: "The-Interdependency/ucns",
    to: "The-Interdependency/METAPAT",
    kind: "planned_input",
    source_block: "DEPENDENCIES",
    source_id: "metapat_planned_flow_edges",
  },
  {
    from: "The-Interdependency/METAPAT",
    to: "The-Interdependency/edcm",
    kind: "planned_output",
    source_block: "DEPENDENCIES",
    source_id: "metapat_planned_flow_edges",
  },
];

const collection: MsdmdCollection = {
  repo: "The-Interdependency/METAPAT",
  declarations,
  gaps,
  edges,
};

export default collection;
